-- Agents: simple verification state
CREATE TABLE IF NOT EXISTS "AGENTS" (
    "ID" VARCHAR(255) PRIMARY KEY,
    "STATUS" VARCHAR(50) NOT NULL,
    "CREATED_AT" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    "UPDATED_AT" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);
