-- Documents: stored files linked to a tenancy (e.g., AST, compliance)
CREATE TABLE IF NOT EXISTS "DOCUMENTS" (
    "ID" UUID PRIMARY KEY,
    "TENANCY_ID" UUID NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    "TYPE" VARCHAR(100) NOT NULL,
    "URL" VARCHAR(500),
    "SHARED_WITH" VARCHAR(20) NOT NULL,
    "CREATED_AT" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);
