-- Drop legacy lower-case tables to avoid clashes after renaming
DROP TABLE IF EXISTS maintenance_requests CASCADE;
DROP TABLE IF EXISTS properties CASCADE;
DROP TABLE IF EXISTS tenancies CASCADE;
DROP TABLE IF EXISTS documents CASCADE;
DROP TABLE IF EXISTS agents CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS invites CASCADE;

-- Drop uppercase tables before re-creating
DROP TABLE IF EXISTS "SESSIONS" CASCADE;
DROP TABLE IF EXISTS "MAINTENANCE_REQUESTS" CASCADE;
DROP TABLE IF EXISTS "PROPERTIES" CASCADE;
DROP TABLE IF EXISTS "TENANCIES" CASCADE;
DROP TABLE IF EXISTS "DOCUMENTS" CASCADE;
DROP TABLE IF EXISTS "AGENTS" CASCADE;
DROP TABLE IF EXISTS "USERS" CASCADE;
DROP TABLE IF EXISTS "INVITES" CASCADE;
