-- Invites: track tenancy invitations
CREATE TABLE IF NOT EXISTS "INVITES" (
    "ID" UUID PRIMARY KEY,
    "TENANT_EMAIL" VARCHAR(255) NOT NULL,
    "TENANT_ID" VARCHAR(255),
    "TENANCY_ID" UUID,
    "INVITER_ROLE" VARCHAR(50),
    "INVITER_NAME" VARCHAR(255),
    "PROPERTY_ADDRESS" VARCHAR(255),
    "INVITEE_ROLE" VARCHAR(50) DEFAULT 'tenant',
    "STATUS" VARCHAR(50) NOT NULL,
    "CREATED_AT" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);
