-- Maintenance requests table for landlord-scoped tickets
CREATE TABLE IF NOT EXISTS "MAINTENANCE_REQUESTS" (
    "ID" UUID PRIMARY KEY,
    "LANDLORD_ID" VARCHAR(255) NOT NULL,
    "PROPERTY_ID" VARCHAR(255),
    "TITLE" VARCHAR(255) NOT NULL,
    "DESCRIPTION" TEXT,
    "STATUS" VARCHAR(50) NOT NULL,
    "CREATED_AT" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    "UPDATED_AT" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS "IDX_MAINTENANCE_LANDLORD_STATUS"
    ON "MAINTENANCE_REQUESTS" ("LANDLORD_ID", "STATUS");
