-- Properties catalog
CREATE TABLE IF NOT EXISTS "PROPERTIES" (
    "ID" VARCHAR(255) PRIMARY KEY,
    "LANDLORD_ID" VARCHAR(255) NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    "ADDRESS" VARCHAR(255),
    "POSTCODE" VARCHAR(50),
    "RENT" INTEGER,
    "STATUS" VARCHAR(50) NOT NULL DEFAULT 'Vacant',
    "PAID" BOOLEAN NOT NULL DEFAULT FALSE,
    "CREATED_AT" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);
