CREATE TABLE IF NOT EXISTS "TENANCIES" (
    "ID" UUID PRIMARY KEY,
    "LANDLORD_ID" VARCHAR(255) NOT NULL,
    "PROPERTY_ID" VARCHAR(255) NOT NULL,
    "TENANT_ID" VARCHAR(255) NOT NULL,
    "TENANT_NAME" VARCHAR(255),
    "TENANT_EMAIL" VARCHAR(255),
    "OWNER_ID" VARCHAR(255),
    "OWNER_EMAIL" VARCHAR(255),
    "START_DATE" VARCHAR(50),
    "MONTHLY_RENT" INTEGER,
    "TENANT_STATUS" VARCHAR(50) NOT NULL,
    "INVITE_SENT_AT" TIMESTAMP WITHOUT TIME ZONE,
    "INVITE_ACCEPTED_AT" TIMESTAMP WITHOUT TIME ZONE,
    "REFERENCE_STATUS" VARCHAR(50),
    "AGREEMENT_STATUS" VARCHAR(50),
    "CREATED_AT" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    "UPDATED_AT" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);
