-- Users: basic directory for invite lookups
CREATE TABLE IF NOT EXISTS "USERS" (
    "ID" UUID PRIMARY KEY,
    "EMAIL" VARCHAR(255) UNIQUE NOT NULL,
    "ROLE" VARCHAR(50) NOT NULL,
    "NAME" VARCHAR(255),
    "PHONE" VARCHAR(50),
    "COMPANY_NAME" VARCHAR(255),
    "CREATED_AT" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);
